---
abstract: 'x refs '
author:
  - 'LNATION <thisusedtobeanemail@gmail.com>'
build_requires:
  Import::Export: '0.06'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: overload-x
no_index:
  directory:
    - t
    - inc
requires:
  Function::Fallback::CoreOrPP: '0'
  perl: '5.006'
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
